### ISSUE TITLE
Referencing tables in init.sql

### ISSUE THREAD

**Issue by HettieM** [fac19/Bechdel-Beyond-backend#25]
You can reference other tables to create links in your database. 
e.g. after line 36: FOREIGN KEY user_id INTEGER REFERENCES users(id) ON UPDATE CASCADE ON DELETE CASCADE 

The CASCADE means that if information in users table changes it will be reflected in other tables. 

If you're not referencing a primary key you can just put REFERENCES 

line 52? movAPI_id REFERENCES user_reviews(movAPI_id)

**Comment by glrta** [comment]
Thank you, Hettie, for pointing this out. We just fixed it today to do some joined tables :)
