### ISSUE TITLE
Documentation suggestions:

### ISSUE THREAD

**Issue by Joepock123** [fac19/Bechdel-Beyond-backend#28]
Amazing readme guys. As a potential user of your API a few things regarding my UX. 

- Going through the readme it's not 100% clear what movies I am getting back at the `/films` endpoint. Will this return all films ever created? How many films will I get back etc. 
- When hitting the `/film/:title` endpoint I couldn't find Bad Boys which was very upsetting. Perhaps you could talk more about the API you are using and the constraints on these endpoints.

But in short, smashed it so far.

![nice](https://media0.giphy.com/media/xTiTnBMEz7zAKs57LG/200.gif?cid=e1bb72ff8fa914c917c609125e5a22c8a6815934bf88e3be&rid=200.gif)

**Comment by glrta** [comment]
Thank you for pointing this out, Joe. I hope it makes more sense now.
