### ISSUE TITLE
Getting an error with fetch script

### ISSUE THREAD

**Issue by jackherizsmith** [fac19/Bechdel-Beyond-backend#62]
[`npm run fetch`: TypeError: Cannot set property 'length' of undefined](https://github.com/fac19/Bechdel-Beyond-backend/blob/364054e8903e2251be19e4143f6b1967d478790c/database/fetch.js#L175)

**Comment by glrta** [comment]
You need the API keys for the array to be defined :)

**Comment by jamesj-0** [comment]
You also need to initialise your database with at least one user in order to run the SQL commands
